files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        he: iw
        id: in
        pt-PT: pt
        es-ES: es
        sv-SE: sv
