files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        af: af
        ar: ar
        ca: ca
        cs: cs
        da: da
        nl: nl
        fi: fi
        fr: fr
        de: de
        el: el
        he: iw
        hu: hu
        it: it
        ja: ja
        ko: ko
        no: no
        pl: pl
        pt-PT: pt
        ro: ro
        ru: ru
        sr: sr
        es-ES: es
        sv-SE: sv
        tr: tr
        uk: uk
        vi: vi
