/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_World */

#ifndef _Included_javax_microedition_m3g_World
#define _Included_javax_microedition_m3g_World
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_World_NONE
#define javax_microedition_m3g_World_NONE 144L
#undef javax_microedition_m3g_World_ORIGIN
#define javax_microedition_m3g_World_ORIGIN 145L
#undef javax_microedition_m3g_World_X_AXIS
#define javax_microedition_m3g_World_X_AXIS 146L
#undef javax_microedition_m3g_World_Y_AXIS
#define javax_microedition_m3g_World_Y_AXIS 147L
#undef javax_microedition_m3g_World_Z_AXIS
#define javax_microedition_m3g_World_Z_AXIS 148L
/*
 * Class:     javax_microedition_m3g_World
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_World__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_World
 * Method:    _setActiveCamera
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_World__1setActiveCamera
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_World
 * Method:    _setBackground
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_World__1setBackground
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_World
 * Method:    _getActiveCamera
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_World__1getActiveCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_World
 * Method:    _getBackground
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_World__1getBackground
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
