/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Background */

#ifndef _Included_javax_microedition_m3g_Background
#define _Included_javax_microedition_m3g_Background
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Background_BORDER
#define javax_microedition_m3g_Background_BORDER 32L
#undef javax_microedition_m3g_Background_REPEAT
#define javax_microedition_m3g_Background_REPEAT 33L
/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _ctor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Background__1ctor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _setColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Background__1setColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _getColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Background__1getColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _setImage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Background__1setImage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _getImage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Background__1getImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _setImageMode
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Background__1setImageMode
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _getImageMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Background__1getImageMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _enable
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Background__1enable
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _isEnabled
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Background__1isEnabled
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _setCrop
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Background__1setCrop
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Background
 * Method:    _getCrop
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Background__1getCrop
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
