/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Image2D */

#ifndef _Included_javax_microedition_m3g_Image2D
#define _Included_javax_microedition_m3g_Image2D
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Image2D_ALPHA
#define javax_microedition_m3g_Image2D_ALPHA 96L
#undef javax_microedition_m3g_Image2D_LUMINANCE
#define javax_microedition_m3g_Image2D_LUMINANCE 97L
#undef javax_microedition_m3g_Image2D_LUMINANCE_ALPHA
#define javax_microedition_m3g_Image2D_LUMINANCE_ALPHA 98L
#undef javax_microedition_m3g_Image2D_RGB
#define javax_microedition_m3g_Image2D_RGB 99L
#undef javax_microedition_m3g_Image2D_RGBA
#define javax_microedition_m3g_Image2D_RGBA 100L
/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _ctorImage
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Image2D__1ctorImage
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _ctorSizePixels
 * Signature: (IIII[B)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Image2D__1ctorSizePixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _ctorSizePixelsPalette
 * Signature: (IIII[B[B)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Image2D__1ctorSizePixelsPalette
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _ctorSize
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Image2D__1ctorSize
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _set
 * Signature: (IIIII[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Image2D__1set
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _isMutable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Image2D__1isMutable
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _getFormat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Image2D__1getFormat
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _getWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Image2D__1getWidth
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Image2D
 * Method:    _getHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Image2D__1getHeight
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
