/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Group */

#ifndef _Included_javax_microedition_m3g_Group
#define _Included_javax_microedition_m3g_Group
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Group_NONE
#define javax_microedition_m3g_Group_NONE 144L
#undef javax_microedition_m3g_Group_ORIGIN
#define javax_microedition_m3g_Group_ORIGIN 145L
#undef javax_microedition_m3g_Group_X_AXIS
#define javax_microedition_m3g_Group_X_AXIS 146L
#undef javax_microedition_m3g_Group_Y_AXIS
#define javax_microedition_m3g_Group_Y_AXIS 147L
#undef javax_microedition_m3g_Group_Z_AXIS
#define javax_microedition_m3g_Group_Z_AXIS 148L
/*
 * Class:     javax_microedition_m3g_Group
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Group__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Group
 * Method:    _addChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Group__1addChild
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Group
 * Method:    _removeChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Group__1removeChild
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Group
 * Method:    _getChildCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Group__1getChildCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Group
 * Method:    _getChild
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Group__1getChild
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_Group
 * Method:    _pick3D
 * Signature: (JI[F[F)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Group__1pick3D
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray);

/*
 * Class:     javax_microedition_m3g_Group
 * Method:    _pick2D
 * Signature: (JIFFJ[F)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Group__1pick2D
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
