/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Graphics3D */

#ifndef _Included_javax_microedition_m3g_Graphics3D
#define _Included_javax_microedition_m3g_Graphics3D
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Graphics3D_ANTIALIAS
#define javax_microedition_m3g_Graphics3D_ANTIALIAS 2L
#undef javax_microedition_m3g_Graphics3D_DITHER
#define javax_microedition_m3g_Graphics3D_DITHER 4L
#undef javax_microedition_m3g_Graphics3D_TRUE_COLOR
#define javax_microedition_m3g_Graphics3D_TRUE_COLOR 8L
#undef javax_microedition_m3g_Graphics3D_OVERWRITE
#define javax_microedition_m3g_Graphics3D_OVERWRITE 16L
/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Graphics3D__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _addRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1addRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _addLight
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Graphics3D__1addLight
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _bindGraphics
 * Signature: (JJIIIIIIZIZ[I)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Graphics3D__1bindGraphics
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jboolean, jint, jboolean, jobject);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _bindImage
 * Signature: (JJZI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1bindImage
  (JNIEnv *, jclass, jlong, jlong, jboolean, jint);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _releaseGraphics
 * Signature: (JJZZ[I)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1releaseGraphics
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean, jobject);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _releaseImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1releaseImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _resetLights
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1resetLights
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _clear
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1clear
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _render
 * Signature: (JJJJ[BI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1render
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jbyteArray, jint);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _renderNode
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1renderNode
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _renderWorld
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1renderWorld
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _setCamera
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1setCamera
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _setViewport
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1setViewport
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _setLight
 * Signature: (JIJ[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1setLight
  (JNIEnv *, jclass, jlong, jint, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _setDepthRange
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1setDepthRange
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getViewTransform
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Graphics3D__1getViewTransform
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getCamera
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Graphics3D__1getCamera
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getLightTransform
 * Signature: (JI[B)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Graphics3D__1getLightTransform
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getLightCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Graphics3D__1getLightCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getDepthRangeNear
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_Graphics3D__1getDepthRangeNear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getDepthRangeFar
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_Graphics3D__1getDepthRangeFar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getViewportX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Graphics3D__1getViewportX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getViewportY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Graphics3D__1getViewportY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getViewportWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Graphics3D__1getViewportWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _getViewportHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Graphics3D__1getViewportHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _isAASupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Graphics3D__1isAASupported
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Graphics3D
 * Method:    _isProperRenderer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Graphics3D__1isProperRenderer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
