/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_VertexBuffer */

#ifndef _Included_javax_microedition_m3g_VertexBuffer
#define _Included_javax_microedition_m3g_VertexBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _ctor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexBuffer__1ctor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setColors
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setColors
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setNormals
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setNormals
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setTexCoords
 * Signature: (IIIF[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setTexCoords
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloatArray);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setVertices
 * Signature: (IIF[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setVertices
  (JNIEnv *, jclass, jint, jint, jfloat, jfloatArray);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setDefaultColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setDefaultColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _getDefaultColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexBuffer__1getDefaultColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _getArray
 * Signature: (II[F)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexBuffer__1getArray
  (JNIEnv *, jclass, jint, jint, jfloatArray);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _getVertexCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexBuffer__1getVertexCount
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
