/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_AnimationTrack */

#ifndef _Included_javax_microedition_m3g_AnimationTrack
#define _Included_javax_microedition_m3g_AnimationTrack
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_AnimationTrack_ALPHA
#define javax_microedition_m3g_AnimationTrack_ALPHA 256L
#undef javax_microedition_m3g_AnimationTrack_AMBIENT_COLOR
#define javax_microedition_m3g_AnimationTrack_AMBIENT_COLOR 257L
#undef javax_microedition_m3g_AnimationTrack_COLOR
#define javax_microedition_m3g_AnimationTrack_COLOR 258L
#undef javax_microedition_m3g_AnimationTrack_CROP
#define javax_microedition_m3g_AnimationTrack_CROP 259L
#undef javax_microedition_m3g_AnimationTrack_DENSITY
#define javax_microedition_m3g_AnimationTrack_DENSITY 260L
#undef javax_microedition_m3g_AnimationTrack_DIFFUSE_COLOR
#define javax_microedition_m3g_AnimationTrack_DIFFUSE_COLOR 261L
#undef javax_microedition_m3g_AnimationTrack_EMISSIVE_COLOR
#define javax_microedition_m3g_AnimationTrack_EMISSIVE_COLOR 262L
#undef javax_microedition_m3g_AnimationTrack_FAR_DISTANCE
#define javax_microedition_m3g_AnimationTrack_FAR_DISTANCE 263L
#undef javax_microedition_m3g_AnimationTrack_FIELD_OF_VIEW
#define javax_microedition_m3g_AnimationTrack_FIELD_OF_VIEW 264L
#undef javax_microedition_m3g_AnimationTrack_INTENSITY
#define javax_microedition_m3g_AnimationTrack_INTENSITY 265L
#undef javax_microedition_m3g_AnimationTrack_MORPH_WEIGHTS
#define javax_microedition_m3g_AnimationTrack_MORPH_WEIGHTS 266L
#undef javax_microedition_m3g_AnimationTrack_NEAR_DISTANCE
#define javax_microedition_m3g_AnimationTrack_NEAR_DISTANCE 267L
#undef javax_microedition_m3g_AnimationTrack_ORIENTATION
#define javax_microedition_m3g_AnimationTrack_ORIENTATION 268L
#undef javax_microedition_m3g_AnimationTrack_PICKABILITY
#define javax_microedition_m3g_AnimationTrack_PICKABILITY 269L
#undef javax_microedition_m3g_AnimationTrack_SCALE
#define javax_microedition_m3g_AnimationTrack_SCALE 270L
#undef javax_microedition_m3g_AnimationTrack_SHININESS
#define javax_microedition_m3g_AnimationTrack_SHININESS 271L
#undef javax_microedition_m3g_AnimationTrack_SPECULAR_COLOR
#define javax_microedition_m3g_AnimationTrack_SPECULAR_COLOR 272L
#undef javax_microedition_m3g_AnimationTrack_SPOT_ANGLE
#define javax_microedition_m3g_AnimationTrack_SPOT_ANGLE 273L
#undef javax_microedition_m3g_AnimationTrack_SPOT_EXPONENT
#define javax_microedition_m3g_AnimationTrack_SPOT_EXPONENT 274L
#undef javax_microedition_m3g_AnimationTrack_TRANSLATION
#define javax_microedition_m3g_AnimationTrack_TRANSLATION 275L
#undef javax_microedition_m3g_AnimationTrack_VISIBILITY
#define javax_microedition_m3g_AnimationTrack_VISIBILITY 276L
/*
 * Class:     javax_microedition_m3g_AnimationTrack
 * Method:    _ctor
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_AnimationTrack__1ctor
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     javax_microedition_m3g_AnimationTrack
 * Method:    _getController
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_AnimationTrack__1getController
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationTrack
 * Method:    _getSequence
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_AnimationTrack__1getSequence
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationTrack
 * Method:    _getTargetProperty
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationTrack__1getTargetProperty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationTrack
 * Method:    _setController
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationTrack__1setController
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
