/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Interface */

#ifndef _Included_javax_microedition_m3g_Interface
#define _Included_javax_microedition_m3g_Interface
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Interface_ANIMATION_CONTROLLER
#define javax_microedition_m3g_Interface_ANIMATION_CONTROLLER 1L
#undef javax_microedition_m3g_Interface_ANIMATION_TRACK
#define javax_microedition_m3g_Interface_ANIMATION_TRACK 2L
#undef javax_microedition_m3g_Interface_APPEARANCE
#define javax_microedition_m3g_Interface_APPEARANCE 3L
#undef javax_microedition_m3g_Interface_BACKGROUND
#define javax_microedition_m3g_Interface_BACKGROUND 4L
#undef javax_microedition_m3g_Interface_CAMERA
#define javax_microedition_m3g_Interface_CAMERA 5L
#undef javax_microedition_m3g_Interface_COMPOSITING_MODE
#define javax_microedition_m3g_Interface_COMPOSITING_MODE 6L
#undef javax_microedition_m3g_Interface_FOG
#define javax_microedition_m3g_Interface_FOG 7L
#undef javax_microedition_m3g_Interface_GROUP
#define javax_microedition_m3g_Interface_GROUP 8L
#undef javax_microedition_m3g_Interface_IMAGE_2D
#define javax_microedition_m3g_Interface_IMAGE_2D 9L
#undef javax_microedition_m3g_Interface_INDEX_BUFFER
#define javax_microedition_m3g_Interface_INDEX_BUFFER 10L
#undef javax_microedition_m3g_Interface_KEYFRAME_SEQUENCE
#define javax_microedition_m3g_Interface_KEYFRAME_SEQUENCE 11L
#undef javax_microedition_m3g_Interface_LIGHT
#define javax_microedition_m3g_Interface_LIGHT 12L
#undef javax_microedition_m3g_Interface_LOADER
#define javax_microedition_m3g_Interface_LOADER 13L
#undef javax_microedition_m3g_Interface_MATERIAL
#define javax_microedition_m3g_Interface_MATERIAL 14L
#undef javax_microedition_m3g_Interface_MESH
#define javax_microedition_m3g_Interface_MESH 15L
#undef javax_microedition_m3g_Interface_MORPHING_MESH
#define javax_microedition_m3g_Interface_MORPHING_MESH 16L
#undef javax_microedition_m3g_Interface_POLYGON_MODE
#define javax_microedition_m3g_Interface_POLYGON_MODE 17L
#undef javax_microedition_m3g_Interface_RENDER_CONTEXT
#define javax_microedition_m3g_Interface_RENDER_CONTEXT 18L
#undef javax_microedition_m3g_Interface_SKINNED_MESH
#define javax_microedition_m3g_Interface_SKINNED_MESH 19L
#undef javax_microedition_m3g_Interface_SPRITE_3D
#define javax_microedition_m3g_Interface_SPRITE_3D 20L
#undef javax_microedition_m3g_Interface_TEXTURE_2D
#define javax_microedition_m3g_Interface_TEXTURE_2D 21L
#undef javax_microedition_m3g_Interface_VERTEX_ARRAY
#define javax_microedition_m3g_Interface_VERTEX_ARRAY 22L
#undef javax_microedition_m3g_Interface_VERTEX_BUFFER
#define javax_microedition_m3g_Interface_VERTEX_BUFFER 23L
#undef javax_microedition_m3g_Interface_WORLD
#define javax_microedition_m3g_Interface_WORLD 24L
/*
 * Class:     javax_microedition_m3g_Interface
 * Method:    _ctor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Interface__1ctor
  (JNIEnv *, jclass);

/*
 * Class:     javax_microedition_m3g_Interface
 * Method:    _getClassID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Interface__1getClassID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
