/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_VertexArray */

#ifndef _Included_javax_microedition_m3g_VertexArray
#define _Included_javax_microedition_m3g_VertexArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _ctor
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexArray__1ctor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _setByte
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1setByte
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _setShort
 * Signature: (III[S)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1setShort
  (JNIEnv *, jclass, jint, jint, jint, jshortArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getByte
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1getByte
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getShort
 * Signature: (III[S)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1getShort
  (JNIEnv *, jclass, jint, jint, jint, jshortArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getComponentCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexArray__1getComponentCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getComponentType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexArray__1getComponentType
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getVertexCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexArray__1getVertexCount
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
