/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_AnimationController */

#ifndef _Included_javax_microedition_m3g_AnimationController
#define _Included_javax_microedition_m3g_AnimationController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_AnimationController__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setActiveInterval
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setActiveInterval
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getActiveIntervalStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationController__1getActiveIntervalStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getActiveIntervalEnd
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationController__1getActiveIntervalEnd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setSpeed
 * Signature: (JFI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setSpeed
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getSpeed
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_AnimationController__1getSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setPosition
 * Signature: (JFI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setPosition
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getPosition
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_AnimationController__1getPosition
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setWeight
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setWeight
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getWeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_AnimationController__1getWeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getRefWorldTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationController__1getRefWorldTime
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
