/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Loader_PeekInputStream */

#ifndef _Included_javax_microedition_m3g_Loader_PeekInputStream
#define _Included_javax_microedition_m3g_Loader_PeekInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Loader_PeekInputStream_MAX_SKIP_BUFFER_SIZE
#define javax_microedition_m3g_Loader_PeekInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
