/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_VertexArray */

#ifndef _Included_javax_microedition_m3g_VertexArray
#define _Included_javax_microedition_m3g_VertexArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _ctor
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_VertexArray__1ctor
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _setByte
 * Signature: (JII[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1setByte
  (JNIEnv *, jclass, jlong, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _setShort
 * Signature: (JII[S)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1setShort
  (JNIEnv *, jclass, jlong, jint, jint, jshortArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getByte
 * Signature: (JII[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1getByte
  (JNIEnv *, jclass, jlong, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getShort
 * Signature: (JII[S)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexArray__1getShort
  (JNIEnv *, jclass, jlong, jint, jint, jshortArray);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getComponentCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexArray__1getComponentCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getComponentType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexArray__1getComponentType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_VertexArray
 * Method:    _getVertexCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexArray__1getVertexCount
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
