/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Object3D */

#ifndef _Included_javax_microedition_m3g_Object3D
#define _Included_javax_microedition_m3g_Object3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _addAnimationTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1addAnimationTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _removeAnimationTrack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Object3D__1removeAnimationTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _getAnimationTrackCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1getAnimationTrackCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _animate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1animate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _setUserID
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Object3D__1setUserID
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _getUserID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1getUserID
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _addRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Object3D__1addRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _getAnimationTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1getAnimationTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _duplicate
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1duplicate
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _getReferences
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1getReferences
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     javax_microedition_m3g_Object3D
 * Method:    _find
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Object3D__1find
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
