/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Mesh */

#ifndef _Included_javax_microedition_m3g_Mesh
#define _Included_javax_microedition_m3g_Mesh
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Mesh_NONE
#define javax_microedition_m3g_Mesh_NONE 144L
#undef javax_microedition_m3g_Mesh_ORIGIN
#define javax_microedition_m3g_Mesh_ORIGIN 145L
#undef javax_microedition_m3g_Mesh_X_AXIS
#define javax_microedition_m3g_Mesh_X_AXIS 146L
#undef javax_microedition_m3g_Mesh_Y_AXIS
#define javax_microedition_m3g_Mesh_Y_AXIS 147L
#undef javax_microedition_m3g_Mesh_Z_AXIS
#define javax_microedition_m3g_Mesh_Z_AXIS 148L
/*
 * Class:     javax_microedition_m3g_Mesh
 * Method:    _ctor
 * Signature: (JJ[J[J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Mesh__1ctor
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jlongArray);

/*
 * Class:     javax_microedition_m3g_Mesh
 * Method:    _setAppearance
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Mesh__1setAppearance
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     javax_microedition_m3g_Mesh
 * Method:    _getAppearance
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Mesh__1getAppearance
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_Mesh
 * Method:    _getIndexBuffer
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Mesh__1getIndexBuffer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_Mesh
 * Method:    _getVertexBuffer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Mesh__1getVertexBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Mesh
 * Method:    _getSubmeshCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Mesh__1getSubmeshCount
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
