/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_AnimationController */

#ifndef _Included_javax_microedition_m3g_AnimationController
#define _Included_javax_microedition_m3g_AnimationController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _ctor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationController__1ctor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setActiveInterval
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setActiveInterval
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getActiveIntervalStart
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationController__1getActiveIntervalStart
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getActiveIntervalEnd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationController__1getActiveIntervalEnd
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setSpeed
 * Signature: (IFI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setSpeed
  (JNIEnv *, jclass, jint, jfloat, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getSpeed
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_AnimationController__1getSpeed
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setPosition
 * Signature: (IFI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setPosition
  (JNIEnv *, jclass, jint, jfloat, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getPosition
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_AnimationController__1getPosition
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _setWeight
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_AnimationController__1setWeight
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getWeight
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_AnimationController__1getWeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_AnimationController
 * Method:    _getRefWorldTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_AnimationController__1getRefWorldTime
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
