/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Fog */

#ifndef _Included_javax_microedition_m3g_Fog
#define _Included_javax_microedition_m3g_Fog
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Fog_EXPONENTIAL
#define javax_microedition_m3g_Fog_EXPONENTIAL 80L
#undef javax_microedition_m3g_Fog_LINEAR
#define javax_microedition_m3g_Fog_LINEAR 81L
/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _ctor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Fog__1ctor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _setMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Fog__1setMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _getMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Fog__1getMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _setLinear
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Fog__1setLinear
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _getDistance
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_Fog__1getDistance
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _setDensity
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Fog__1setDensity
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _getDensity
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_Fog__1getDensity
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _setColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Fog__1setColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Fog
 * Method:    _getColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Fog__1getColor
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
