/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Texture2D */

#ifndef _Included_javax_microedition_m3g_Texture2D
#define _Included_javax_microedition_m3g_Texture2D
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Texture2D_FILTER_BASE_LEVEL
#define javax_microedition_m3g_Texture2D_FILTER_BASE_LEVEL 208L
#undef javax_microedition_m3g_Texture2D_FILTER_LINEAR
#define javax_microedition_m3g_Texture2D_FILTER_LINEAR 209L
#undef javax_microedition_m3g_Texture2D_FILTER_NEAREST
#define javax_microedition_m3g_Texture2D_FILTER_NEAREST 210L
#undef javax_microedition_m3g_Texture2D_FUNC_ADD
#define javax_microedition_m3g_Texture2D_FUNC_ADD 224L
#undef javax_microedition_m3g_Texture2D_FUNC_BLEND
#define javax_microedition_m3g_Texture2D_FUNC_BLEND 225L
#undef javax_microedition_m3g_Texture2D_FUNC_DECAL
#define javax_microedition_m3g_Texture2D_FUNC_DECAL 226L
#undef javax_microedition_m3g_Texture2D_FUNC_MODULATE
#define javax_microedition_m3g_Texture2D_FUNC_MODULATE 227L
#undef javax_microedition_m3g_Texture2D_FUNC_REPLACE
#define javax_microedition_m3g_Texture2D_FUNC_REPLACE 228L
#undef javax_microedition_m3g_Texture2D_WRAP_CLAMP
#define javax_microedition_m3g_Texture2D_WRAP_CLAMP 240L
#undef javax_microedition_m3g_Texture2D_WRAP_REPEAT
#define javax_microedition_m3g_Texture2D_WRAP_REPEAT 241L
/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _ctor
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1ctor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _setImage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Texture2D__1setImage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _getImage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1getImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _setFiltering
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Texture2D__1setFiltering
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _setWrapping
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Texture2D__1setWrapping
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _getWrappingS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1getWrappingS
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _getWrappingT
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1getWrappingT
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _setBlending
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Texture2D__1setBlending
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _getBlending
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1getBlending
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _setBlendColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Texture2D__1setBlendColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _getBlendColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1getBlendColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _getImageFilter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1getImageFilter
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Texture2D
 * Method:    _getLevelFilter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Texture2D__1getLevelFilter
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
