/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Loader */

#ifndef _Included_javax_microedition_m3g_Loader
#define _Included_javax_microedition_m3g_Loader
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Loader_PNG_IHDR
#define javax_microedition_m3g_Loader_PNG_IHDR 1229472850L
#undef javax_microedition_m3g_Loader_PNG_tRNS
#define javax_microedition_m3g_Loader_PNG_tRNS 1951551059L
#undef javax_microedition_m3g_Loader_PNG_IDAT
#define javax_microedition_m3g_Loader_PNG_IDAT 1229209940L
#undef javax_microedition_m3g_Loader_JPEG_JFIF
#define javax_microedition_m3g_Loader_JPEG_JFIF 1246120262L
#undef javax_microedition_m3g_Loader_JPEG_SOFn_DELTA
#define javax_microedition_m3g_Loader_JPEG_SOFn_DELTA 7L
#undef javax_microedition_m3g_Loader_JPEG_INVALID_COLOUR_FORMAT
#define javax_microedition_m3g_Loader_JPEG_INVALID_COLOUR_FORMAT -1L
#undef javax_microedition_m3g_Loader_INVALID_HEADER_TYPE
#define javax_microedition_m3g_Loader_INVALID_HEADER_TYPE -1L
#undef javax_microedition_m3g_Loader_M3G_TYPE
#define javax_microedition_m3g_Loader_M3G_TYPE 0L
#undef javax_microedition_m3g_Loader_PNG_TYPE
#define javax_microedition_m3g_Loader_PNG_TYPE 1L
#undef javax_microedition_m3g_Loader_JPEG_TYPE
#define javax_microedition_m3g_Loader_JPEG_TYPE 2L
#undef javax_microedition_m3g_Loader_AVG_HEADER_SEC_LENGTH
#define javax_microedition_m3g_Loader_AVG_HEADER_SEC_LENGTH 64L
#undef javax_microedition_m3g_Loader_AVG_XREF_SEC_LENGTH
#define javax_microedition_m3g_Loader_AVG_XREF_SEC_LENGTH 128L
/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _inflate
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Loader__1inflate
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _ctor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Loader__1ctor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _decodeData
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Loader__1decodeData
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _setExternalReferences
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Loader__1setExternalReferences
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _getLoadedObjects
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Loader__1getLoadedObjects
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _getObjectsWithUserParameters
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Loader__1getObjectsWithUserParameters
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _getNumUserParameters
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Loader__1getNumUserParameters
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Loader
 * Method:    _getUserParameter
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Loader__1getUserParameter
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
