/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_TriangleStripArray */

#ifndef _Included_javax_microedition_m3g_TriangleStripArray
#define _Included_javax_microedition_m3g_TriangleStripArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_TriangleStripArray
 * Method:    _createImplicit
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_TriangleStripArray__1createImplicit
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     javax_microedition_m3g_TriangleStripArray
 * Method:    _createExplicit
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_TriangleStripArray__1createExplicit
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     javax_microedition_m3g_TriangleStripArray
 * Method:    _getIndexCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_TriangleStripArray__1getIndexCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_TriangleStripArray
 * Method:    _getIndices
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_TriangleStripArray__1getIndices
  (JNIEnv *, jclass, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
