/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Node */

#ifndef _Included_javax_microedition_m3g_Node
#define _Included_javax_microedition_m3g_Node
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Node_NONE
#define javax_microedition_m3g_Node_NONE 144L
#undef javax_microedition_m3g_Node_ORIGIN
#define javax_microedition_m3g_Node_ORIGIN 145L
#undef javax_microedition_m3g_Node_X_AXIS
#define javax_microedition_m3g_Node_X_AXIS 146L
#undef javax_microedition_m3g_Node_Y_AXIS
#define javax_microedition_m3g_Node_Y_AXIS 147L
#undef javax_microedition_m3g_Node_Z_AXIS
#define javax_microedition_m3g_Node_Z_AXIS 148L
/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getTransformTo
 * Signature: (II[B)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Node__1getTransformTo
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _align
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Node__1align
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _setAlignment
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Node__1setAlignment
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _setAlphaFactor
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Node__1setAlphaFactor
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getAlphaFactor
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_Node__1getAlphaFactor
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _enable
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Node__1enable
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _isEnabled
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Node__1isEnabled
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _setScope
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Node__1setScope
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getScope
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Node__1getScope
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getParent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Node__1getParent
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getZRef
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Node__1getZRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getYRef
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Node__1getYRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getSubtreeSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Node__1getSubtreeSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     javax_microedition_m3g_Node
 * Method:    _getAlignmentTarget
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Node__1getAlignmentTarget
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
