/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_KeyframeSequence */

#ifndef _Included_javax_microedition_m3g_KeyframeSequence
#define _Included_javax_microedition_m3g_KeyframeSequence
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_KeyframeSequence_LINEAR
#define javax_microedition_m3g_KeyframeSequence_LINEAR 176L
#undef javax_microedition_m3g_KeyframeSequence_SLERP
#define javax_microedition_m3g_KeyframeSequence_SLERP 177L
#undef javax_microedition_m3g_KeyframeSequence_SPLINE
#define javax_microedition_m3g_KeyframeSequence_SPLINE 178L
#undef javax_microedition_m3g_KeyframeSequence_SQUAD
#define javax_microedition_m3g_KeyframeSequence_SQUAD 179L
#undef javax_microedition_m3g_KeyframeSequence_STEP
#define javax_microedition_m3g_KeyframeSequence_STEP 180L
#undef javax_microedition_m3g_KeyframeSequence_CONSTANT
#define javax_microedition_m3g_KeyframeSequence_CONSTANT 192L
#undef javax_microedition_m3g_KeyframeSequence_LOOP
#define javax_microedition_m3g_KeyframeSequence_LOOP 193L
/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _ctor
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_KeyframeSequence__1ctor
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _setValidRange
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_KeyframeSequence__1setValidRange
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _setKeyframe
 * Signature: (JII[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_KeyframeSequence__1setKeyframe
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _setDuration
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_KeyframeSequence__1setDuration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getDuration
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _setRepeatMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_KeyframeSequence__1setRepeatMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getRepeatMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getRepeatMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getComponentCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getComponentCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getInterpolationType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getInterpolationType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getKeyframe
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getKeyframe
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getKeyframeCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getKeyframeCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getValidRangeFirst
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getValidRangeFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_KeyframeSequence
 * Method:    _getValidRangeLast
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_KeyframeSequence__1getValidRangeLast
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
