/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Camera */

#ifndef _Included_javax_microedition_m3g_Camera
#define _Included_javax_microedition_m3g_Camera
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Camera_NONE
#define javax_microedition_m3g_Camera_NONE 144L
#undef javax_microedition_m3g_Camera_ORIGIN
#define javax_microedition_m3g_Camera_ORIGIN 145L
#undef javax_microedition_m3g_Camera_X_AXIS
#define javax_microedition_m3g_Camera_X_AXIS 146L
#undef javax_microedition_m3g_Camera_Y_AXIS
#define javax_microedition_m3g_Camera_Y_AXIS 147L
#undef javax_microedition_m3g_Camera_Z_AXIS
#define javax_microedition_m3g_Camera_Z_AXIS 148L
#undef javax_microedition_m3g_Camera_GENERIC
#define javax_microedition_m3g_Camera_GENERIC 48L
#undef javax_microedition_m3g_Camera_PARALLEL
#define javax_microedition_m3g_Camera_PARALLEL 49L
#undef javax_microedition_m3g_Camera_PERSPECTIVE
#define javax_microedition_m3g_Camera_PERSPECTIVE 50L
/*
 * Class:     javax_microedition_m3g_Camera
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Camera__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Camera
 * Method:    _setParallel
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Camera__1setParallel
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Camera
 * Method:    _setPerspective
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Camera__1setPerspective
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Camera
 * Method:    _setGeneric
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Camera__1setGeneric
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Camera
 * Method:    _getProjectionAsTransform
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Camera__1getProjectionAsTransform
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Camera
 * Method:    _getProjectionAsParams
 * Signature: (J[F)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Camera__1getProjectionAsParams
  (JNIEnv *, jclass, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
