/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_CompositingMode */

#ifndef _Included_javax_microedition_m3g_CompositingMode
#define _Included_javax_microedition_m3g_CompositingMode
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_CompositingMode_ALPHA
#define javax_microedition_m3g_CompositingMode_ALPHA 64L
#undef javax_microedition_m3g_CompositingMode_ALPHA_ADD
#define javax_microedition_m3g_CompositingMode_ALPHA_ADD 65L
#undef javax_microedition_m3g_CompositingMode_MODULATE
#define javax_microedition_m3g_CompositingMode_MODULATE 66L
#undef javax_microedition_m3g_CompositingMode_MODULATE_X2
#define javax_microedition_m3g_CompositingMode_MODULATE_X2 67L
#undef javax_microedition_m3g_CompositingMode_REPLACE
#define javax_microedition_m3g_CompositingMode_REPLACE 68L
/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_CompositingMode__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _setBlending
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_CompositingMode__1setBlending
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _getBlending
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_CompositingMode__1getBlending
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _setAlphaThreshold
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_CompositingMode__1setAlphaThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _getAlphaThreshold
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_CompositingMode__1getAlphaThreshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _setAlphaWriteEnable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_CompositingMode__1setAlphaWriteEnable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _isAlphaWriteEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_CompositingMode__1isAlphaWriteEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _enableDepthTest
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_CompositingMode__1enableDepthTest
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _isDepthTestEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_CompositingMode__1isDepthTestEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _enableDepthWrite
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_CompositingMode__1enableDepthWrite
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _isDepthWriteEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_CompositingMode__1isDepthWriteEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _enableColorWrite
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_CompositingMode__1enableColorWrite
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _isColorWriteEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_CompositingMode__1isColorWriteEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _setDepthOffset
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_CompositingMode__1setDepthOffset
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _getDepthOffsetFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_CompositingMode__1getDepthOffsetFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_CompositingMode
 * Method:    _getDepthOffsetUnits
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_CompositingMode__1getDepthOffsetUnits
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
