/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Appearance */

#ifndef _Included_javax_microedition_m3g_Appearance
#define _Included_javax_microedition_m3g_Appearance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Appearance__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _getCompositingMode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Appearance__1getCompositingMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _getFog
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Appearance__1getFog
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _getLayer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Appearance__1getLayer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _getMaterial
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Appearance__1getMaterial
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _getPolygonMode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Appearance__1getPolygonMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _getTexture
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Appearance__1getTexture
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _setCompositingMode
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Appearance__1setCompositingMode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _setFog
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Appearance__1setFog
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _setLayer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Appearance__1setLayer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _setMaterial
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Appearance__1setMaterial
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _setPolygonMode
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Appearance__1setPolygonMode
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Appearance
 * Method:    _setTexture
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Appearance__1setTexture
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
