/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_RayIntersection */

#ifndef _Included_javax_microedition_m3g_RayIntersection
#define _Included_javax_microedition_m3g_RayIntersection
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
