/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Graphics3D_Destroyer */

#ifndef _Included_javax_microedition_m3g_Graphics3D_Destroyer
#define _Included_javax_microedition_m3g_Graphics3D_Destroyer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
