/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_SkinnedMesh */

#ifndef _Included_javax_microedition_m3g_SkinnedMesh
#define _Included_javax_microedition_m3g_SkinnedMesh
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_SkinnedMesh_NONE
#define javax_microedition_m3g_SkinnedMesh_NONE 144L
#undef javax_microedition_m3g_SkinnedMesh_ORIGIN
#define javax_microedition_m3g_SkinnedMesh_ORIGIN 145L
#undef javax_microedition_m3g_SkinnedMesh_X_AXIS
#define javax_microedition_m3g_SkinnedMesh_X_AXIS 146L
#undef javax_microedition_m3g_SkinnedMesh_Y_AXIS
#define javax_microedition_m3g_SkinnedMesh_Y_AXIS 147L
#undef javax_microedition_m3g_SkinnedMesh_Z_AXIS
#define javax_microedition_m3g_SkinnedMesh_Z_AXIS 148L
/*
 * Class:     javax_microedition_m3g_SkinnedMesh
 * Method:    _ctor
 * Signature: (JJ[J[JJ)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_SkinnedMesh__1ctor
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jlongArray, jlong);

/*
 * Class:     javax_microedition_m3g_SkinnedMesh
 * Method:    _addTransform
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_SkinnedMesh__1addTransform
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_SkinnedMesh
 * Method:    _getSkeleton
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_SkinnedMesh__1getSkeleton
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_SkinnedMesh
 * Method:    _getBoneTransform
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_SkinnedMesh__1getBoneTransform
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_SkinnedMesh
 * Method:    _getBoneVertices
 * Signature: (JJ[I[F)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_SkinnedMesh__1getBoneVertices
  (JNIEnv *, jclass, jlong, jlong, jintArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
