/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Transform */

#ifndef _Included_javax_microedition_m3g_Transform
#define _Included_javax_microedition_m3g_Transform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _mul
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1mul
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _setIdentity
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1setIdentity
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _setMatrix
 * Signature: ([B[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1setMatrix
  (JNIEnv *, jclass, jbyteArray, jfloatArray);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _getMatrix
 * Signature: ([B[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1getMatrix
  (JNIEnv *, jclass, jbyteArray, jfloatArray);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _invert
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1invert
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _transpose
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1transpose
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _rotate
 * Signature: ([BFFFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1rotate
  (JNIEnv *, jclass, jbyteArray, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _rotateQuat
 * Signature: ([BFFFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1rotateQuat
  (JNIEnv *, jclass, jbyteArray, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _scale
 * Signature: ([BFFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1scale
  (JNIEnv *, jclass, jbyteArray, jfloat, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _translate
 * Signature: ([BFFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1translate
  (JNIEnv *, jclass, jbyteArray, jfloat, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _transformTable
 * Signature: ([B[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1transformTable
  (JNIEnv *, jclass, jbyteArray, jfloatArray);

/*
 * Class:     javax_microedition_m3g_Transform
 * Method:    _transformArray
 * Signature: ([BJ[FZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transform__1transformArray
  (JNIEnv *, jclass, jbyteArray, jlong, jfloatArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
