/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_VertexBuffer */

#ifndef _Included_javax_microedition_m3g_VertexBuffer
#define _Included_javax_microedition_m3g_VertexBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_VertexBuffer__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setColors
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setColors
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setNormals
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setNormals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setTexCoords
 * Signature: (JIJF[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setTexCoords
  (JNIEnv *, jclass, jlong, jint, jlong, jfloat, jfloatArray);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setVertices
 * Signature: (JJF[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setVertices
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloatArray);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _setDefaultColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_VertexBuffer__1setDefaultColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _getDefaultColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexBuffer__1getDefaultColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _getArray
 * Signature: (JI[F)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_VertexBuffer__1getArray
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     javax_microedition_m3g_VertexBuffer
 * Method:    _getVertexCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_VertexBuffer__1getVertexCount
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
