/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Material */

#ifndef _Included_javax_microedition_m3g_Material
#define _Included_javax_microedition_m3g_Material
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Material_AMBIENT
#define javax_microedition_m3g_Material_AMBIENT 1024L
#undef javax_microedition_m3g_Material_DIFFUSE
#define javax_microedition_m3g_Material_DIFFUSE 2048L
#undef javax_microedition_m3g_Material_EMISSIVE
#define javax_microedition_m3g_Material_EMISSIVE 4096L
#undef javax_microedition_m3g_Material_SPECULAR
#define javax_microedition_m3g_Material_SPECULAR 8192L
/*
 * Class:     javax_microedition_m3g_Material
 * Method:    _ctor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Material__1ctor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Material
 * Method:    _setColor
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Material__1setColor
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     javax_microedition_m3g_Material
 * Method:    _getColor
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Material__1getColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_Material
 * Method:    _setShininess
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Material__1setShininess
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     javax_microedition_m3g_Material
 * Method:    _getShininess
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_javax_microedition_m3g_Material__1getShininess
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Material
 * Method:    _setVertexColorTrackingEnable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Material__1setVertexColorTrackingEnable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     javax_microedition_m3g_Material
 * Method:    _isVertexColorTrackingEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Material__1isVertexColorTrackingEnabled
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
