/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Sprite3D */

#ifndef _Included_javax_microedition_m3g_Sprite3D
#define _Included_javax_microedition_m3g_Sprite3D
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_microedition_m3g_Sprite3D_NONE
#define javax_microedition_m3g_Sprite3D_NONE 144L
#undef javax_microedition_m3g_Sprite3D_ORIGIN
#define javax_microedition_m3g_Sprite3D_ORIGIN 145L
#undef javax_microedition_m3g_Sprite3D_X_AXIS
#define javax_microedition_m3g_Sprite3D_X_AXIS 146L
#undef javax_microedition_m3g_Sprite3D_Y_AXIS
#define javax_microedition_m3g_Sprite3D_Y_AXIS 147L
#undef javax_microedition_m3g_Sprite3D_Z_AXIS
#define javax_microedition_m3g_Sprite3D_Z_AXIS 148L
/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _ctor
 * Signature: (JZJJ)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Sprite3D__1ctor
  (JNIEnv *, jclass, jlong, jboolean, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _isScaled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_microedition_m3g_Sprite3D__1isScaled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _setAppearance
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Sprite3D__1setAppearance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _setImage
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Sprite3D__1setImage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _setCrop
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Sprite3D__1setCrop
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _getCrop
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_javax_microedition_m3g_Sprite3D__1getCrop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _getAppearance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Sprite3D__1getAppearance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javax_microedition_m3g_Sprite3D
 * Method:    _getImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_javax_microedition_m3g_Sprite3D__1getImage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
