/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_microedition_m3g_Transformable */

#ifndef _Included_javax_microedition_m3g_Transformable
#define _Included_javax_microedition_m3g_Transformable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _setOrientation
 * Signature: (JFFFFZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1setOrientation
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _preRotate
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1preRotate
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _getOrientation
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1getOrientation
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _setScale
 * Signature: (JFFFZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1setScale
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _getScale
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1getScale
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _setTranslation
 * Signature: (JFFFZ)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1setTranslation
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _getTranslation
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1getTranslation
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _setTransform
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1setTransform
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _getTransform
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1getTransform
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     javax_microedition_m3g_Transformable
 * Method:    _getComposite
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_javax_microedition_m3g_Transformable__1getComposite
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
