name: Build
on:
  # Trigger on every pull request and on push
  # to the `main` branch.
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Gradle version
        run: ./gradlew --version 
      - name: Change permission
        run: chmod +x ./gradlew
      - name: Build the app
        run: ./gradlew build
      - name: Upload apk 
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/dev/release/*.apk

